### ISSUE TITLE
toml文件中的字符串可以作为富文本渲染吗？

### ISSUE THREAD

**Issue by syan2023** [qianxi0410/cv.typ#3]
查了半天官方文档没查到办法🌿

例如如果我想在 points = ["text",] 中给部分文本加粗，但现在会把 *text*, #strong[text] 这些写法全都当成纯文本渲染出来

请问dalao知道有什么合适的解法么？

**Comment by syan2023** [comment]
找到了——可以用 [eval](https://typst.app/docs/reference/foundations/eval/) 方法 🤦‍♂️

**Comment by qianxi0410** [comment]
按理来说我这个应该支持，我最新的commit来看，用eval可以做到 @syan2023

**Comment by syan2023** [comment]
> 按理来说我这个应该支持，我最新的commit来看，用eval可以做到 @syan2023

感谢！刚刚一直在用#award.name一栏激情调试，发现能用eval方法之后才意识到原来之前已经高亮好了🤦‍♂️只是默认字体是英文，#strong[中文]高亮不出来（🌿太抽象了

顺便感谢作者的简历模板——
